/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RegistrationController;
import Model.LoginModel;
import Model.RegistrationModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahas Suraweers
 */
public class Regeistration extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Regeistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cancel = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_u = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_p = new javax.swing.JTextField();
        txt_r = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_a = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_em = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_m = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_n = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ln = new javax.swing.JTextField();
        txt_e = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setMinimumSize(new java.awt.Dimension(1040, 500));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cancel.setBackground(new java.awt.Color(0, 51, 204));
        btn_cancel.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Back");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 310, 40));

        btn_register.setBackground(new java.awt.Color(0, 51, 204));
        btn_register.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 320, 40));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_u.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel1.add(txt_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setText("UserName ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 50));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 50));

        txt_p.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        txt_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pActionPerformed(evt);
            }
        });
        jPanel1.add(txt_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        txt_r.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel1.add(txt_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 30));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel8.setText("Retype password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 400, 250));

        btn_clear.setBackground(new java.awt.Color(0, 51, 204));
        btn_clear.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 320, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_a.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 360, 60));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 152, 52));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setText("Email");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 152, 52));

        txt_em.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_em, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 360, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel7.setText("Mobile");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 152, 50));

        txt_m.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 360, 30));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 152, 52));

        txt_fn.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, 30));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel6.setText("NIC");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 152, 52));

        txt_n.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 360, 30));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 152, 52));

        txt_ln.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 30));

        txt_e.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel2.add(txt_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 360, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 152, 52));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 570, 400));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel11.setText("Complete your registration");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 350, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        try {
            String firstName = txt_fn.getText();
            String lastName = txt_ln.getText();
            String nic = txt_n.getText();
            String mobile = txt_m.getText();
            String email = txt_em.getText();
            String address = txt_a.getText();
            String employeeIDStr = txt_e.getText();
            String username = txt_u.getText();
            String password = String.valueOf(txt_p.getText());
            String retypePassword = String.valueOf(txt_r.getText());

            // Validations
            if (firstName.isEmpty() || lastName.isEmpty() || nic.isEmpty() || mobile.isEmpty() || email.isEmpty() || address.isEmpty()
                    || employeeIDStr.isEmpty() || username.isEmpty() || password.isEmpty() || retypePassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!password.equals(retypePassword)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int employeeID = Integer.parseInt(employeeIDStr);

            // Create an instance of Model and Controller
            RegistrationModel model = new RegistrationModel();
            RegistrationController controller = new RegistrationController(model);

            // Perform the registration
            boolean isRegistered = controller.addEmployeeWithLogin(firstName, lastName, nic, mobile, email, address, employeeID, username, password);

            if (isRegistered) {
                JOptionPane.showMessageDialog(this, "Registration Successful!");
            } else {
                JOptionPane.showMessageDialog(this, "Registration Failed.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Clear all fields regardless of the result
            clearFields();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

   
    private void clearFields() {
        txt_fn.setText("");
        txt_ln.setText("");
        txt_n.setText("");
        txt_m.setText("");
        txt_em.setText("");
        txt_a.setText("");
        txt_e.setText("");
        txt_u.setText("");
        txt_p.setText("");
        txt_r.setText("");
    


    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        
        Login n = new Login();
        n.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_fn.setText("");
        txt_ln.setText("");
        txt_n.setText("");
        txt_m.setText("");
        txt_em.setText("");
        txt_a.setText("");
        txt_e.setText("");
        txt_u.setText("");
        txt_p.setText("");
        txt_r.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_e;
    private javax.swing.JTextField txt_em;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JTextField txt_m;
    private javax.swing.JTextField txt_n;
    private javax.swing.JTextField txt_p;
    private javax.swing.JTextField txt_r;
    private javax.swing.JTextField txt_u;
    // End of variables declaration//GEN-END:variables
}
